

    
    
    let Settees = [
        {
          Title: "Rovel Solid Wood Settee In Brown Colour",
          Price: "₹ 12,014",
          img1: "https://ii1.pepperfry.com/media/catalog/product/r/o/568x625/rovel-solid-wood-settee-in-brown-colour---bohemiana-by-pepperfry-rovel-solid-wood-settee-in-brown-co-cbfxcg.jpg",
          img2: "https://ii1.pepperfry.com/media/catalog/product/r/o/568x625/rovel-solid-wood-settee-in-brown-colour---bohemiana-by-pepperfry-rovel-solid-wood-settee-in-brown-co-xyq6bc.jpg",
          img3: "https://ii1.pepperfry.com/media/catalog/product/r/o/568x625/rovel-solid-wood-settee-in-brown-colour---bohemiana-by-pepperfry-rovel-solid-wood-settee-in-brown-co-6cnd3b.jpg",
          Brand: " Bohemiana",
          Dimensions: "H 28 X W 40 X D 18 (All Dimension Are In Inches)",
          Weight: " 10.4 KG",
          Colour: "Brown",
          Warranty: "36 Months Warranty",
          Assembly: " Carpenter Assembly",
          Primary_Material: "Mango Wood",
          Room_Type: "Living Room",
          Seating_Height: "16.75",
        },
        {
          Title: "Symes Solid Wood Sette In Honey Oak Finish",
          Price: "₹ 17,390",
          img1: "https://ii1.pepperfry.com/media/catalog/product/s/y/568x625/symes-solid-wood-bench-in-honey-oak-finish---amberville-by-pepperfry-symes-solid-wood-bench-in-honey-k93hqa.jpg",
          img2: "https://ii1.pepperfry.com/media/catalog/product/s/y/568x625/symes-solid-wood-bench-in-honey-oak-finish-by-amberville-symes-solid-wood-bench-in-honey-oak-finish--1psgkx.jpg",
          img3: "https://ii1.pepperfry.com/media/catalog/product/s/y/568x625/symes-solid-wood-bench-in-honey-oak-finish-by-amberville-symes-solid-wood-bench-in-honey-oak-finish--cotgyk.jpg",
          Brand: "Amberville",
          Dimensions:
            " H 37 x W 48 x D 19; Seating Height - 18 (All dimension in inches)",
          Weight: " 20 KG",
          Colour: "Honey Oak",
          Warranty: " 36 Months' Warranty",
          Assembly: " No Assembly Required",
          Primary_Material: " Sheesham Wood",
          Room_Type: " Living Room",
          Seating_Height: " 18",
        },
        {
          Title: "Ludwig Solid Wood Settee In Natural Finish",
          Price: "₹ 19,799",
          img1: "https://ii1.pepperfry.com/media/catalog/product/l/u/568x625/ludwig-solid-wood-bench-in-natural-finish---bohemiana-by-pepperfry-ludwig-solid-wood-bench-in-natura-t1fmh3.jpg",
          img2: "https://ii1.pepperfry.com/media/catalog/product/l/u/568x625/ludwig-solid-wood-console-table-in-natural-finish---bohemiana-by-pepperfry-ludwig-solid-wood-console-8hcngq.jpg",
          img3: "https://ii1.pepperfry.com/media/catalog/product/l/u/568x625/ludwig-solid-wood-console-table-in-natural-finish---bohemiana-by-pepperfry-ludwig-solid-wood-console-kpvezc.jpg",
          Brand: " Bohemiana",
          Dimensions: " H 24 x W 35.5 x D 15.25 (All Dimension Are In Inches)",
          Weight: " 30 KG",
          Colour: " Natural",
          Warranty: "36 Months' Warranty",
          Assembly: " Carpenter Assembly",
          Primary_Material: "Mango Wood",
          Room_Type: "Living Room",
        },
        {
          Title: "Orpha Metal Settee In Grey Colour",
          Price: "₹ 9,344",
          img1: "https://ii1.pepperfry.com/media/catalog/product/o/r/568x625/orpha-metal-settee-in-grey-colour---bohemiana-by-pepperfry-orpha-metal-settee-in-grey-colour---bohem-uoaipu.jpg",
          img2: "https://ii1.pepperfry.com/media/catalog/product/o/r/568x625/orpha-metal-settee-in-grey-colour---bohemiana-by-pepperfry-orpha-metal-settee-in-grey-colour---bohem-tqsrtm.jpg",
          img3: "https://ii1.pepperfry.com/media/catalog/product/o/r/568x625/orpha-metal-settee-in-grey-colour---bohemiana-by-pepperfry-orpha-metal-settee-in-grey-colour---bohem-mejtxw.jpg",
          Brand: " Bohemiana",
          Dimensions: "H 22 X W 41.5 X D 20 (All Dimension Are In Inches)",
          Weight: " 9.2 KG",
          Colour: " Grey / Black",
          Warranty: " 36 Months' Warranty",
          Assembly: " Carpenter Assembly",
          Primary_Material: "Metal",
          Room_Type: " Living Room",
          Seating_Height: "17",
        },
        {
          Title: "Maurya Solid Wood Settee In Honey Oak Finish",
          Price: "₹ 22,133",
          img1: "https://ii1.pepperfry.com/media/catalog/product/m/a/568x625/maurya-solid-wood-settee-in-honey-oak-finish---mudramark-by-pepperfry-maurya-solid-wood-settee-in-ho-edv7r6.jpg",
          img2: "https://ii1.pepperfry.com/media/catalog/product/a/m/568x625/amherst-settee-in-honey-oak-finish-by-amberville-amherst-settee-in-honey-oak-finish-by-amberville-lre7kf.jpg",
          img3: "https://ii1.pepperfry.com/media/catalog/product/a/m/568x625/amherst-settee-in-honey-oak-finish-by-amberville-amherst-settee-in-honey-oak-finish-by-amberville-gavfmr.jpg",
          Brand: "Mudramark",
          Dimensions: "H 37 x W 47 x D 19 (In Inches)",
          Weight: "25 KG",
          Colour: "Honey Oak",
          Warranty: "36 Months' Warranty",
          Assembly: " No Assembly Required",
          Primary_Material: "Sheesham Wood",
          Room_Type: "Living Room",
          Seating_Height: "18",
        },
        {
          Title: "Maurya Solid Wood Settee In Passion Mahogany Finish",
          Price: "₹ 22,133",
          img1: "https://ii1.pepperfry.com/media/catalog/product/m/a/568x625/maurya-solid-wood-settee-in-passion-mahogany-finish---mudramark-by-pepperfry-maurya-solid-wood-sette-axebb2.jpg",
          img2: "https://ii1.pepperfry.com/media/catalog/product/a/m/568x625/amherst-settee-in-passion-mahogany-finish-by-amberville-amherst-settee-in-passion-mahogany-finish-by-nbf4mc.jpg",
          img3: "https://ii1.pepperfry.com/media/catalog/product/m/a/568x625/maurya-solid-wood-handcrafted-settee-in-passion-mahogany-finish-by-mudramark-maurya-solid-wood-handc-pqeb47.jpg",
          Brand: "Mudramark",
          Dimensions: "H 36 x W 63 x D 20(all dimensions in inches)",
          Weight: "25 KG",
          Colour: "Passion Mahogany",
          Warranty: "36 Months' Warranty",
          Assembly: "No Assembly Required",
          Primary_Material: "Mango Wood",
          Room_Type: "Living Room",
          Seating_Height: "18",
        },
        {
          Title: "Thiva Metal Settee In Matte Black Finish",
          Price: "₹ 13,349",
          img1: "https://ii1.pepperfry.com/media/catalog/product/t/h/568x625/thiva-metal-bench-in-black-matte-finish---bohemiana-by-pepperfry-thiva-metal-bench-in-black-matte-fi-5ozqzk.jpg",
          img2: "https://ii1.pepperfry.com/media/catalog/product/t/h/568x625/thiva-metal-bench-in-black-matte-finish---bohemiana-by-pepperfry-thiva-metal-bench-in-black-matte-fi-qzpbxl.jpg",
          img3: "https://ii1.pepperfry.com/media/catalog/product/t/h/568x625/thiva-metal-bench-in-black-matte-finish---bohemiana-by-pepperfry-thiva-metal-bench-in-black-matte-fi-eef09a.jpg",
          Brand: "Bohemiana",
          Dimensions: "H 24 x W 46 x D 20(All dimension are in Inches)",
          Weight: "21 KG",
          Colour: "Black",
          Warranty: " 36 Months' Warranty",
          Assembly: "No Assembly Required",
          Primary_Material: "Iron",
          Room_Type: " Living Room",
          Seating_Height: "15",
        },
        {
          Title: "Rafles Settee in Brown Colour",
          Price: "₹ 13,349",
          img1: "https://ii1.pepperfry.com/media/catalog/product/r/a/568x625/rafles-settee-in-brown-colour-by-stories-rafles-settee-in-brown-colour-by-stories-zfjims.jpg",
          img2: "https://ii1.pepperfry.com/media/catalog/product/r/a/568x625/rafles-two-seater-bench-in-brown-colour-by-stories-rafles-two-seater-bench-in-brown-colour-by-storie-6zfwp4.jpg",
          img3: "https://ii1.pepperfry.com/media/catalog/product/r/a/568x625/rafles-two-seater-bench-in-brown-colour-by-stories-rafles-two-seater-bench-in-brown-colour-by-storie-arnvva.jpg",
          Brand: "Stories",
          Dimensions:
            "H 34 x W 46 x D 19; Seating Height : 18(all dimensions are in inches)",
          Weight: "10 KG",
          Warranty: "12 Months' Warranty",
          Assembly: "No Assembly Required",
          Primary_Material: "Teak Wood",
          Room_Type: "Living Room",
          Seating_Height: "18",
        },
      ];
    
      localStorage.setItem("Settees",JSON.stringify(Settees))
    
      let Benches = [
        {
          Title: "Siramika Solid Wood Bench In Honey Oak Finish",
          Price: "₹ 19,064",
          img1: "https://ii1.pepperfry.com/media/catalog/product/s/i/568x625/siramika-solid-wood-bench-in-honey-oak-finish---mudramark-by-pepperfry-siramika-solid-wood-bench-in--nwiuvi.jpg",
          img2: "https://ii1.pepperfry.com/media/catalog/product/s/i/568x625/siramika-solid-wood-bench-in-honey-oak-finish-by-mudramark-siramika-solid-wood-bench-in-honey-oak-fi-zgh1kc.jpg",
          img3: "https://ii1.pepperfry.com/media/catalog/product/s/i/568x625/siramika-solid-wood-bench-in-honey-oak-finish-by-mudramark-siramika-solid-wood-bench-in-honey-oak-fi-neo8bq.jpg",
          Brand: "Mudramark",
          Dimensions: "H 17 x W 46 x D 19(all dimensions in inches)",
          Weight: "21.8 KG",
          Colour: "Honey Oak",
          Warranty: "36 Months' Warranty",
          Assembly: "Carpenter Assembly",
          Primary_Material: "Sheesham Wood",
          Room_Type: "Living Room",
          Collection: "Siramika",
        },
        {
          Title: "Reed Bench in Provincial Teak Finish",
          Price: "₹ 18,971",
          img1: "https://ii1.pepperfry.com/media/catalog/product/r/e/568x625/reed-bench-in-provincial-teak-finish---woodsworth-by-pepperfry-reed-bench-in-provincial-teak-finish--mkztow.jpg",
          img2: "https://ii1.pepperfry.com/media/catalog/product/r/e/568x625/reed-upholstered-bench-in-provincial-teak-finish-by-woodsworth-reed-upholstered-bench-in-provincial--9xsuxp.jpg",
          img3: "https://ii1.pepperfry.com/media/catalog/product/r/e/568x625/reed-bench-in-provincial-teak-finish-by-woodsworth-reed-bench-in-provincial-teak-finish-by-woodswort-f15hx4.jpg",
          Brand: "Woodsworth",
          Dimensions:
            " H 16 x W 46 x D 16; Seating Height-16 (all dimensions in inches)",
          Weight: "25.2 KG",
          Colour: "Provincial Teak",
          Warranty: " 36 Months' Warranty",
          Assembly: " No Assembly Required",
          Primary_Material: "Sheesham Wood",
          Room_Type: " Living Room",
          Seating_Height: "16",
        },
        {
          Title: "Oscar Bench",
          Price: "₹ 13,794",
          img1: "https://ii1.pepperfry.com/media/catalog/product/o/s/568x625/oscar-bench-by-bohemiana-oscar-bench-by-bohemiana-yyxb2k.jpg",
          img2: "https://ii1.pepperfry.com/media/catalog/product/o/s/1100x1210/oscar-bench-by-bohemiana-oscar-bench-by-bohemiana-oefzem.jpg",
          img3: "https://ii1.pepperfry.com/media/catalog/product/o/s/568x625/oscar-bench-by-bohemiana-oscar-bench-by-bohemiana-b4amax.jpg",
          Brand: "Bohemiana",
          Dimensions: " H 19 x W 51 x D 13 (All Dimensions in Inches)",
          Weight: "18 KG",
          Warranty: "36 Months' Warranty",
          Assembly: " No Assembly Required",
          Primary_Material: "Mango Wood",
          Room_Type: "Living Room",
        },
        {
          Title: "Athens Solid Wood Bench in Provincial Teak Finish",
          Price: "₹ 8,799",
          img1: "https://ii1.pepperfry.com/media/catalog/product/a/t/568x625/athens-solid-wood-bench-in-provincial-teak-finish---woodsworth-by-pepperfry-athens-solid-wood-bench--g2palg.jpg",
          img2: "https://ii1.pepperfry.com/media/catalog/product/a/t/568x625/athens-solid-wood-bench-in-provincial-teak-finish-by-woodsworth-athens-solid-wood-bench-in-provincia-b7ovuu.jpg",
          img3: "https://ii1.pepperfry.com/media/catalog/product/a/t/568x625/athens-solid-wood-bench-in-provincial-teak-finish-by-woodsworth-athens-solid-wood-bench-in-provincia-lbbev2.jpg",
          Brand: "Woodsworth",
          Dimensions:
            "H 18 x W 44 x D 16; Seating Height-18 (All Dimensions in Inches)",
          Weight: "10.8 KG",
          Colour: "Provincial Teak",
          Warranty: "36 Months' Warranty",
          Assembly: "No Assembly Required",
          Primary_Material: "Sheesham Wood",
          Room_Type: "Dining Room",
          Seating_Height: "18",
        },
    
        {
          Title: "Bench In Black Finish",
          Price: "₹ 7,394 ",
          img1: "https://ii1.pepperfry.com/media/catalog/product/b/e/1100x1210/bench-in-black-finish---bohemiana-by-pepperfry-bench-in-black-finish---bohemiana-by-pepperfry-zdxwgp.jpg",
          img2: "https://ii1.pepperfry.com/media/catalog/product/b/e/568x625/bench-in-black-finish-by-bohemiana-bench-in-black-finish-by-bohemiana-ecvmen.jpg",
          img3: "https://ii1.pepperfry.com/media/catalog/product/b/e/568x625/bench-in-black-finish-by-bohemiana-bench-in-black-finish-by-bohemiana-szfspq.jpg",
          Brand: "Bohemiana",
          Dimensions:
            "H 18.1 x W 39.4 x D 15.9; Seating Height-18 (All Dimensions in Inches)",
          Weight: "9 KG",
          Colour: "Black",
          Warranty: "36 Months' Warranty",
          Assembly: "Carpenter Assembly",
          Primary_Material: "Metal",
          Room_Type: "Living Room",
          Seating_Height: " 18",
        },
    
        {
          Title: "Nuevo Solid Wood Dining Bench In Honey Oak Finish",
          Price: "₹ 8,799 ",
          img1: "https://ii1.pepperfry.com/media/catalog/product/n/u/568x625/nuevo-solid-wood-dining-bench-in-honey-oak-finish---woodsworth-by-pepperfry-nuevo-solid-wood-dining--fdn4wh.jpg",
          img2: "https://ii1.pepperfry.com/media/catalog/product/n/u/568x625/nuevo-solid-wood-dining-bench-in-honey-oak-finish---woodsworth-by-pepperfry-nuevo-solid-wood-dining--njicub.jpg",
          img2: "https://ii1.pepperfry.com/media/catalog/product/n/u/568x625/nuevo-solid-wood-dining-bench-in-honey-oak-finish---woodsworth-by-pepperfry-nuevo-solid-wood-dining--6iclrh.jpg",
          Brand: " Woodsworth",
          Dimensions: " H : 17.8 x W : 45.3 x D : 15 (All Dimension In Inches)",
          Weight: " 24 KG",
          Colour: " Honey Oak",
          Warranty: "36 Months' Warranty",
          Assembly: "Carpenter Assembly",
          Primary_Material: "Sheesham Wood",
          Room_Type: " Living Room",
          Seating_Height: "18",
          Top_Material: "Solid Wood",
        },
        {
          Title: "Rafael Bench In Provincial Teak Finish",
          Price: "₹ 16,909",
          img1: "https://ii1.pepperfry.com/media/catalog/product/r/a/568x625/rafael-bench-in-provincial-teak-finish---bohemiana-by-pepperfry-rafael-bench-in-provincial-teak-fini-mmqxjc.jpg",
          img2: "https://ii1.pepperfry.com/media/catalog/product/r/a/568x625/rafael-upholstered-bench-in-provincial-teak-finish-by-bohemiana-rafael-upholstered-bench-in-provinci-jeitl5.jpg",
          img3: "https://ii1.pepperfry.com/media/catalog/product/r/a/568x625/rafael-upholstered-bench-in-provincial-teak-finish-by-bohemiana-rafael-upholstered-bench-in-provinci-qlupa5.jpg",
          Brand: "Bohemiana",
          Dimensions: " H 18 x W 52 x D 18 (all dimensions in inches)Weight: 15 KG",
          Colour: "Provincial Teak",
          Warranty: " 36 Months' Warranty",
          Assembly: "No Assembly Required",
          Primary_Material: "Sheesham Wood",
          Room_Type: "Living Room",
          Seating_Height: "18",
        },
        {
          Title: "Artava Solid Wood Bench In Warm Chestnut Finish",
          Price: "₹ 11,879",
          img1: "https://ii1.pepperfry.com/media/catalog/product/a/r/568x625/artava-solid-wood-bench-in-warm-chestnut-finish---mudramark-by-pepperfry-artava-solid-wood-bench-in--qggiet.jpg",
          img2: "https://ii1.pepperfry.com/media/catalog/product/a/r/1100x1210/artava-bench-in-warm-chestnut-finish-by-mudramark-artava-bench-in-warm-chestnut-finish-by-mudramark-6fozf1.jpg",
          img3: "https://ii1.pepperfry.com/media/catalog/product/a/r/568x625/artava-bench-in-warm-chestnut-finish-by-mudramark-artava-bench-in-warm-chestnut-finish-by-mudramark-xremvl.jpg",
          Brand: "Mudramark",
          Dimensions: "H 17 x W 47 x D 16(all dimensions in inches)",
          Weight: "10.2 KG",
          Colour: "Warm Chestnut",
          Warranty: "36 Months' Warranty",
          Assembly: "Carpenter Assembly",
          Primary_Material: "Sheesham Wood",
          Room_Type: "Living Room",
          Collection: "Soulful Textiles",
          Seating_Height: "17",
        },
        {
          Title: "Tectona Teak Wood Bench In Provincial Teak Finish",
          Price: "₹ 14,684",
          img1: "https://ii1.pepperfry.com/media/catalog/product/t/e/568x625/tectona-solid-wood-bench-in-provincial-teak-finish---woodsworth-by-pepperfry-tectona-solid-wood-benc-g6huo4.jpg",
          img2: "https://ii1.pepperfry.com/media/catalog/product/t/e/568x625/tectona-solid-wood-bench-in-provincial-teak-finish---woodsworth-by-pepperfry-tectona-solid-wood-benc-frvdqp.jpg",
          img3: "https://ii1.pepperfry.com/media/catalog/product/t/e/568x625/tectona-solid-wood-bench-in-provincial-teak-finish---woodsworth-by-pepperfry-tectona-solid-wood-benc-rwns46.jpg",
          Brand: " Woodsworth",
          Dimensions: " H 18 x W 43 x D 15.7 (All Dimensions in Inches)",
          Weight: "10 KG",
          Colour: "Provincial Teak",
          Warranty: "36 Months' Warranty",
          Assembly: "Carpenter Assembly",
          Primary_Material: "Teak Wood",
          Room_Type: "Living Room",
          Collection: "Tectona",
          Seating_Height: "18 Inches",
        },
      ];
    
      localStorage.setItem("Benches",JSON.stringify(Benches));
      let Chaise_loungers = [
        {
          Title: "Garret Solid Wood Chaise Lounger In Provincial Teak Finish",
          Price: "",
          img1: "https://ii1.pepperfry.com/media/catalog/product/g/a/1100x1210/garret-solid-wood-chaise-lounger-in-provincial-teak-finish---amberville-by-pepperfry-garret-solid-wo-7it9s7.jpg",
          img2: "https://ii1.pepperfry.com/media/catalog/product/g/a/568x625/garret-solid-wood-chaise-lounger-in-provincial-teak-finish-by-bohemiana-garret-solid-wood-chaise-lou-wbqkyn.jpg",
          img3: "https://ii1.pepperfry.com/media/catalog/product/g/a/568x625/garret-solid-wood-chaise-lounger-in-provincial-teak-finish-by-bohemiana-garret-solid-wood-chaise-lou-99kyzx.jpg",
          Brand: " Amberville",
          Dimensions: " Height: 37.8, Width: 74.8, Depth: 27.9 In Inches",
          Weight: "32 KG",
          Colour: "Provincial Teak",
          Warranty: " 36 Months' Warranty",
          Assembly: "Carpenter Assembly",
          Primary_Material: "Sheesham Wood",
          Room_Type: "Living Room",
          Seating_Height: "17",
        },
        {
          Title: "Elle Decor Chaise Lounger In Printed Upholstery",
          Price: "",
          img1: "https://ii1.pepperfry.com/media/catalog/product/e/l/568x625/elle-decor-chaise-lounger-in-printed-upholstery----casacraft-by-pepperfry-elle-decor-chaise-lounger--lmgfge.jpg",
          img2: "https://ii1.pepperfry.com/media/catalog/product/c/a/568x625/calleros-chaise-lounger-in-navy-blue-colour----casacraft-by-pepperfry-calleros-chaise-lounger-in-nav-mvudc7.jpg",
          img3: "https://ii1.pepperfry.com/media/catalog/product/c/a/568x625/calleros-chaise-lounger-in-navy-blue-colour----casacraft-by-pepperfry-calleros-chaise-lounger-in-nav-xtoefg.jpg",
          Brand: "CasaCraft",
          Dimensions: "H 29.5 x W x 72 x D 35 (all dimensions are in inches)",
          Weight: "35 KG",
          Warranty: "36 Months' Warranty",
          Assembly: "Carpenter Assembly",
          Primary_Material: "Velvet Fabric",
          Room_Type: "Living Room",
          Collection: "Elle Decor",
          Seating_Height: "17.5",
        },
        {
          Title: "Barcena Chaise Lounger In Sea Blue Colour",
          Price: "",
          img1: "https://ii1.pepperfry.com/media/catalog/product/b/a/800x880/barcena-chaise-lounger-in-sea-blue-colour---casacraft-by-pepperfry-barcena-chaise-lounger-in-sea-blu-fqnj0h.jpg",
          img2: "https://ii1.pepperfry.com/media/catalog/product/b/a/568x625/barcena-chaise-lounger-in-sea-blue-colour-barcena-chaise-lounger-in-sea-blue-colour-bjg2ph.jpg",
          img3: "https://ii1.pepperfry.com/media/catalog/product/b/a/568x625/barcena-chaise-lounger-in-sea-blue-colour-barcena-chaise-lounger-in-sea-blue-colour-qgqc2a.jpg",
          Brand: "CasaCraft",
          Dimensions: "H 31.5 x W 29 x D 66 (all dimensions are in inches)",
          Weight: "35 KG",
          Warranty: "36 Months' Warranty",
          Assembly: "Carpenter Assembly",
          Primary_Material: "Velvet Fabric",
          Room_Type: "Living Room",
          Seating_Height: "18",
        },
        {
          Title: "Berra Chaise Lounger In Blush Colour",
          Price: "₹ 30,433",
          img1: "https://ii1.pepperfry.com/media/catalog/product/b/e/568x625/berra-chaise-lounger-in-blush-colour----casacraft-by-pepperfry-berra-chaise-lounger-in-blush-colour--krolr0.jpg",
          img2: "https://ii1.pepperfry.com/media/catalog/product/b/e/568x625/berra-chaise-lounger-in-blush-colour----casacraft-by-pepperfry-berra-chaise-lounger-in-blush-colour--snje2a.jpg",
          img3: "https://ii1.pepperfry.com/media/catalog/product/b/e/568x625/berra-chaise-lounger-in-blush-colour----casacraft-by-pepperfry-berra-chaise-lounger-in-blush-colour--trgeoo.jpg",
          Brand: "CasaCraft",
          Dimensions: "H 36 x W 68 x D 28(all dimensions in inches)",
          Weight: "35 KG",
          Warranty: "36 Months' Warranty",
          Assembly: " Carpenter Assembly",
          Primary_Material: " Fabric",
          Room_Type: "Living Room",
          Seating_Height: "16",
        },
        {
          Title: "Canedo Chaise Lounger In Teal Blue Colour",
          Price: "₹ 31,224",
          img1: "https://ii1.pepperfry.com/media/catalog/product/c/a/568x625/canedo-chaise-lounger-in-teal-blue-colour---casacraft-by-pepperfry-canedo-chaise-lounger-in-teal-blu-behxgr.jpg",
          img2: "https://ii1.pepperfry.com/media/catalog/product/c/a/568x625/canedo-chaise-lounger-in-teal-blue-colour-canedo-chaise-lounger-in-teal-blue-colour-kglo0z.jpg",
          img3: "https://ii1.pepperfry.com/media/catalog/product/c/a/568x625/canedo-chaise-lounger-in-teal-blue-colour-canedo-chaise-lounger-in-teal-blue-colour-cgcmny.jpg",
          Brand: "CasaCraft",
          Dimensions: "H 34 x W 30 x D 72 (all dimensions are in inches)",
          Weight: "35 KG",
          Warranty: "36 Months' Warranty",
          Assembly: " Carpenter Assembly",
          Primary_Material: "Velvet Fabric",
          Room_Type: "Living Room",
          Seating_Height: "16",
        },
        {
          Title: "Barcena Chaise Lounger In Olive Green Colour",
          Price: "₹ 27,271",
          img1: "https://ii1.pepperfry.com/media/catalog/product/b/a/568x625/barcena-chaise-lounger-in-olive-green-colour---casacraft-by-pepperfry-barcena-chaise-lounger-in-oliv-tnmv84.jpg",
          img2: "https://ii1.pepperfry.com/media/catalog/product/b/a/568x625/barcena-chaise-lounger-in-green-colour---casacraft-by-pepperfry-barcena-chaise-lounger-in-green-colo-bghjgj.jpg",
          img3: "https://ii1.pepperfry.com/media/catalog/product/b/a/568x625/barcena-chaise-lounger-in-green-colour---casacraft-by-pepperfry-barcena-chaise-lounger-in-green-colo-tgmgjw.jpg",
          Brand: "CasaCraft",
          Dimensions: "H 31.5 x W 29 x D 66 (all dimensions are in inches)",
          Weight: "35 KG",
          Warranty: " 36 Months' Warranty",
          Assembly: "Carpenter Assembly",
          Primary_Material: "Velvet Fabric",
          Room_Type: "Living Room",
          Seating_Height: "18",
        },
        {
          Title: "Harleston Chaise Lounger In Honey Oak Finish",
          Price: "₹ 18,181 ",
          img1: "https://ii1.pepperfry.com/media/catalog/product/h/a/568x625/harleston-chaise-lounger-in-honey-oak-finish---amberville-by-pepperfry-harleston-chaise-lounger-in-h-m3zjho.jpg",
          img2: "https://ii1.pepperfry.com/media/catalog/product/h/a/568x625/harleston-chaise-lounger-in-honey-oak-finish---amberville-by-pepperfry-harleston-chaise-lounger-in-h-hmmskw.jpg",
          img3: "https://ii1.pepperfry.com/media/catalog/product/h/a/568x625/harleston-chaise-lounger-in-honey-oak-finish-by-amberville-harleston-chaise-lounger-in-honey-oak-fin-llx9cb.jpg",
          Brand: "Amberville",
          Dimensions:
            "H 32 x W 60 x D 18; Seating Height-16(all dimensions in inches)",
          Weight: "20 KG",
          Colour: "Honey Oak",
          Warranty: "36 Months' Warranty",
          Assembly: " No Assembly Required",
          Primary_Material: "Sheesham Wood",
          Room_Type: "Living Room",
          Collection: "Harleston",
          Seating_Height: " 16",
        },
        {
          Title: "Calleros Chaise Lounger In Navy Blue Colour",
          Price: "₹ 26,481 ",
          img1: "https://ii1.pepperfry.com/media/catalog/product/c/a/568x625/calleros--chaise-lounger-in-navy-blue-colour---casacraft-by-pepperfry-calleros--chaise-lounger-in-na-sh0gu4.jpg",
          img2: "https://ii1.pepperfry.com/media/catalog/product/c/a/568x625/calleros--chaise-lounger-in-navy-blue-colour-calleros--chaise-lounger-in-navy-blue-colour-bmbnq5.jpg",
          img3: "https://ii1.pepperfry.com/media/catalog/product/c/a/568x625/calleros--chaise-lounger-in-navy-blue-colour-calleros--chaise-lounger-in-navy-blue-colour-kgdrbi.jpg",
          Brand: " CasaCraft",
          Dimensions: " H 29.5 x W 35x D72(all dimensions in inches)",
          Weight: "35 KG",
          Warranty: "36 Months' Warranty",
          Assembly: "Carpenter Assembly",
          Primary_Material: "Fabric",
          Room_Type: "Living Room",
          Seating_Height: "17",
        },
        {
          Title: "Berra Chaise Lounger In Voilet Colour- CasaCraft",
          Price: "₹ 35,176",
          img1: "https://ii1.pepperfry.com/media/catalog/product/b/e/568x625/berra-chaise-lounger-in-voilet-colour--casacraft-by-pepperfry-berra-chaise-lounger-in-voilet-colour--2eisdv.jpg",
          img2: "https://ii1.pepperfry.com/media/catalog/product/b/e/568x625/berra-chaise-lounger-in-wine-colour-berra-chaise-lounger-in-wine-colour-wrg3yb.jpg",
          img3: "https://ii1.pepperfry.com/media/catalog/product/b/e/568x625/berra-chaise-lounger-in-wine-colour-berra-chaise-lounger-in-wine-colour-33iwrg.jpg",
          Brand: "CasaCraft",
          Dimensions: " H 36 x W 28 x D 68(all dimensions in inches)",
          Weight: "35 KG",
          Warranty: "36 Months' Warranty",
          Assembly: "Carpenter Assembly",
          Primary_Material: " Velvet Fabric",
          Room_Type: " Living Room",
          Seating_Height: "16",
        },
      ];
    
      localStorage.setItem("Chaise_loungers",JSON.stringify(Chaise_loungers))
    
      let Recamiers = [
        {
          Title: "Louis Solid Wood Settee In Provincial Teak Finish",
          Price: "₹ 22,133",
          img1: "https://ii1.pepperfry.com/media/catalog/product/l/o/568x625/louis-solid-wood-settee-in-provincial-teak-finish---amberville-by-pepperfry-louis-solid-wood-settee--zmf4re.jpg",
          img2: "https://ii1.pepperfry.com/media/catalog/product/l/o/568x625/louis-solid-wood-settee-in-provincial-teak-finish-by-amberville-louis-solid-wood-settee-in-provincia-796qg7.jpg",
          img3: "https://ii1.pepperfry.com/media/catalog/product/l/o/568x625/louis-solid-wood-settee-in-provincial-teak-finish-by-amberville-louis-solid-wood-settee-in-provincia-nbrukh.jpg",
          Brand: "Amberville",
          Dimensions:
            "H 27 x W 59 x D 20; Seating Height-16 (all dimensions in inches)",
          Weight: "28 KG",
          Colour: "Rustic Teak",
          Warranty: " 36 Months' Warranty",
          Assembly: "No Assembly Required",
          Primary_Material: "Sheesham Wood",
          Room_Type: "Living Room",
          Collection: "Louis",
          Seating_Height: "16",
        },
    
        {
          Title: "Vance Recamier In Honey Oak Finish",
          Price: "₹ 9,239 ",
          img1: "https://ii1.pepperfry.com/media/catalog/product/v/a/1100x1210/vance-recamier-in-honey-oak-finish---amberville-by-pepperfry-vance-recamier-in-honey-oak-finish---am-uraskn.jpg",
          img2: "https://ii1.pepperfry.com/media/catalog/product/v/a/568x625/vance-recamier-in-honey-oak-finish-by-amberville-vance-recamier-in-honey-oak-finish-by-amberville-u6mwcm.jpg",
          img3: "https://ii1.pepperfry.com/media/catalog/product/v/a/568x625/vance-recamier-in-honey-oak-finish-by-amberville-vance-recamier-in-honey-oak-finish-by-amberville-kdadoj.jpg",
          Brand: "Amberville",
          Dimensions:
            " H 23 x W 45 x D 18; Seating Height-18 (All Dimensions in Inches)",
          Weight: " 22 KG",
          Colour: "Honey Oak",
          Warranty: "36 Months' Warranty",
          Assembly: " No Assembly Required",
          Primary_Material: " Sheesham Wood",
          Room_Type: "Living Room",
          Seating_Height: "18",
        },
        {
          Title: "Blaine Solid Wood Recamier in Provincial Teak Finish",
          Price: "₹ 17,390",
          img1: "https://ii1.pepperfry.com/media/catalog/product/b/l/568x625/blaine-solid-wood-recamier-in-provincial-teak-finish---woodsworth-by-pepperfry-blaine-solid-wood-rec-xh8pyk.jpg",
          img2: "https://ii1.pepperfry.com/media/catalog/product/b/l/568x625/blaine-solid-wood-recamier-in-provincial-teak-finish---woodsworth-by-pepperfry-blaine-solid-wood-rec-kcaflc.jpg",
          img3: "https://ii1.pepperfry.com/media/catalog/product/b/l/568x625/blaine-solid-wood-recamier-in-provincial-teak-finish---woodsworth-by-pepperfry-blaine-solid-wood-rec-cc84jq.jpg",
          Brand: "Woodsworth",
          Dimensions: " H 24 x W 47 x D 16 (All Dimension In Inches)",
          Weight: "34 KG",
          Colour: "Provincial Teak",
          Warranty: " 36 Months' Warranty",
          Assembly: " No Assembly Required",
          Primary_Material: "Sheesham Wood",
          Room_Type: "Dining Room",
          Seating_Height: "15",
        },
        {
          Title: "Denise Solid Wood Upholstered Recaimer in Honey Oak Finish",
          Price: "₹ 22,924",
          img1: "https://ii1.pepperfry.com/media/catalog/product/d/e/568x625/denise-solid-wood-upholstered-bench-in-honey-oak-finish---amberville-by-pepperfry-denise-solid-wood--2gvj5l.jpg",
          img2: "https://ii1.pepperfry.com/media/catalog/product/d/e/568x625/denise-solid-wood-upholstered-bench-in-honey-oak-finish---amberville-by-pepperfry-denise-solid-wood--w2uemr.jpg",
          img3: "https://ii1.pepperfry.com/media/catalog/product/d/e/568x625/denise-solid-wood-upholstered-bench-in-honey-oak-finish---amberville-by-pepperfry-denise-solid-wood--fm4rpy.jpg",
          Brand: "Amberville",
          Dimensions: "H 23.6 x W 67 x D 22 (All dimensions are in inches)",
          Weight: " 35 KG",
          Colour: " Honey Oak",
          Warranty: "36 Months' Warranty",
          Assembly: " Carpenter Assembly",
          Primary_Material: "Mango Wood",
          Room_Type: "Living Room",
          Seating_Height: " 19",
        },
        {
          Title: "Mia Recamier with Storage in Brown Colour",
          Price: "₹ 10,119 ",
          img1: "https://ii1.pepperfry.com/media/catalog/product/m/i/568x625/mia-2-seater-ottoman-with-storage-in-brown-colour-by-adorn-homez-mia-2-seater-ottoman-with-storage-i-9ztg9e.jpg",
          img2: "https://ii1.pepperfry.com/media/catalog/product/m/i/568x625/mia-2-seater-ottoman-with-storage-in-brown-colour-by-adorn-homez-mia-2-seater-ottoman-with-storage-i-doeljb.jpg",
          img3: "https://ii1.pepperfry.com/media/catalog/product/m/i/568x625/mia-recamier-with-storage-in-brown-colour-by-adorn-homez-mia-recamier-with-storage-in-brown-colour-b-k4bpws.jpg",
          Brand: "Adorn Homez",
          Dimensions: "H 24 x W 48 x D 18 (All Dimension in Inches)",
          Weight: "20 KG",
          Warranty: "12 Months' Warranty",
          Assembly: "Carpenter Assembly",
          Primary_Material: "Fabric",
          Room_Type: " Living Room",
          Seating_Height: "17",
        },
        {
          Title: "Mia Recamier with Storage in Dark Grey Colour",
          Price: "₹ 10,119",
          img1: "https://ii1.pepperfry.com/media/catalog/product/m/i/568x625/mia-2-seater-ottoman-with-storage-in-dark-grey-colour-by-adorn-homez-mia-2-seater-ottoman-with-stora-s3kxxz.jpg",
          img2: "https://ii1.pepperfry.com/media/catalog/product/m/i/568x625/mia-recamier-with-storage-in-dark-grey-colour-by-adorn-homez-mia-recamier-with-storage-in-dark-grey--yj663r.jpg",
          img3: "https://ii1.pepperfry.com/media/catalog/product/m/i/568x625/mia-2-seater-ottoman-with-storage-in-dark-grey-colour-by-adorn-homez-mia-2-seater-ottoman-with-stora-hwxyrt.jpg",
          Brand: "Adorn Homez",
          Dimensions: " H 24 x W 48 x D 18 (All Dimension in Inches)",
          Weight: "20 KG",
          Warranty: "12 Months' Warranty",
          Assembly: "Carpenter Assembly",
          Primary_Material: "Fabric",
          Room_Type: " Living Room",
          Seating_Height: "17",
        },
        {
          Title: "Avika Solid Wood Recamier In Warm Chestnut Finish",
          Price: "₹ 17,390",
          img1: "https://ii1.pepperfry.com/media/catalog/product/a/v/568x625/avika-solid-wood-recamier-in-warm-chestnut-finish---mudramark-by-pepperfry-avika-solid-wood-recamier-lr7mbq.jpg",
          img2: "https://ii1.pepperfry.com/media/catalog/product/a/v/1100x1210/avika-settee-in-warm-chestnut-finish-by-mudramark-avika-settee-in-warm-chestnut-finish-by-mudramark-gadlyg.jpg",
          img3: "https://ii1.pepperfry.com/media/catalog/product/a/v/568x625/avika-settee-in-warm-chestnut-finish-by-mudramark-avika-settee-in-warm-chestnut-finish-by-mudramark-o9mxuw.jpg",
          Brand: " Mudramark",
          Dimensions: " H 24 x W 54 x D 16(all dimensions in inches)",
          Weight: "15 KG",
          Colour: "Warm Chestnut",
          Warranty: "36 Months' Warranty",
          Assembly: " Carpenter Assembly",
          Primary_Material: "Sheesham Wood",
          Room_Type: "Living Room",
          Collection: " Soulful Textiles",
          Seating_Height: "17",
        },
        {
          Title: "Amelie Recamier In Provincial Teak Finish",
          Price: "₹ 30,433",
          img1: "https://ii1.pepperfry.com/media/catalog/product/a/m/568x625/amelie-recamier-in-provincial-teak-finish---amberville-by-pepperfry-amelie-recamier-in-provincial-te-ajpifx.jpg",
          img2: "https://ii1.pepperfry.com/media/catalog/product/a/m/568x625/amelie-recamier-in-provincial-teak-finish-by-amberville-amelie-recamier-in-provincial-teak-finish-by-u9rny0.jpg",
          img3: "https://ii1.pepperfry.com/media/catalog/product/a/m/568x625/amelie-recamier-in-provincial-teak-finish-by-amberville-amelie-recamier-in-provincial-teak-finish-by-xmi8pd.jpg",
          Brand: "Amberville",
          Dimensions:
            "H 30 x W 70 x D 24; Seating Height-18 (All Dimensions in Inches)",
          Weight: " 45 KG",
          Colour: "Provincial Teak",
          Warranty: "36 Months' Warranty",
          Assembly: " Carpenter Assembly",
          Primary_Material: "Sheesham Wood",
          Room_Type: "Living Room",
          Seating_Height: "18",
        },
        {
          Title: "Molo 3 Seater Recamier With Storage In Royal Blue Colour",
          Price: "₹ 19,779",
          img1: "https://ii1.pepperfry.com/media/catalog/product/m/o/568x625/molo-recamier-in-royal-blue-by-febonic-molo-recamier-in-royal-blue-by-febonic-qdhvzj.jpg",
          img2: "https://ii1.pepperfry.com/media/catalog/product/m/o/568x625/molo-recamier-in-royal-blue-by-febonic-molo-recamier-in-royal-blue-by-febonic-5dy3sa.jpg",
          img3: "https://ii1.pepperfry.com/media/catalog/product/m/o/568x625/molo-recamier-in-royal-blue-by-febonic-molo-recamier-in-royal-blue-by-febonic-sbdthw.jpg",
          Brand: "Febonic",
          Dimensions: " H 23 x W 70 x D 19 (all dimension in inches)",
          Weight: "15 KG",
          Warranty: " 12 Months' Warranty",
          Assembly: "Carpenter Assembly",
          Primary_Material: "Fabric",
          Room_Type: "Living Room",
          Seating_Height: "18",
        },
      ];
    
      localStorage.setItem("Recamiers",JSON.stringify(Recamiers))
    
    
    

   
