

    
    
    let Settees = [
        {
          Title: "Rovel Solid Wood Settee In Brown Colour",
          Price: 34999,
          offer:66,
          img1: "https://ii1.pepperfry.com/media/catalog/product/r/o/568x625/rovel-solid-wood-settee-in-brown-colour---bohemiana-by-pepperfry-rovel-solid-wood-settee-in-brown-co-cbfxcg.jpg",
          img2: "https://ii1.pepperfry.com/media/catalog/product/r/o/568x625/rovel-solid-wood-settee-in-brown-colour---bohemiana-by-pepperfry-rovel-solid-wood-settee-in-brown-co-xyq6bc.jpg",
          img3: "https://ii1.pepperfry.com/media/catalog/product/r/o/568x625/rovel-solid-wood-settee-in-brown-colour---bohemiana-by-pepperfry-rovel-solid-wood-settee-in-brown-co-6cnd3b.jpg",
          Brand: " Bohemiana",
        Dimensions: "H 28 X W 40 X D 18 (All Dimension Are In Inches)",
        dims: [28, 40, 18],
          Weight: " 10.4 KG",
          Colour: "Brown",
          Warranty: "36 Months Warranty",
          Assembly: " Carpenter Assembly",
          Primary_Material: "Mango Wood",
          Room_Type: "Living Room",
          Seating_Height: "16.75",          
        },
        {
          Title: "Symes Solid Wood Sette In Honey Oak Finish",
          Price: 34999,
          offer: 50,
          dims: [37, 48, 19],
          img1: "https://ii1.pepperfry.com/media/catalog/product/s/y/568x625/symes-solid-wood-bench-in-honey-oak-finish---amberville-by-pepperfry-symes-solid-wood-bench-in-honey-k93hqa.jpg",
          img2: "https://ii1.pepperfry.com/media/catalog/product/s/y/568x625/symes-solid-wood-bench-in-honey-oak-finish-by-amberville-symes-solid-wood-bench-in-honey-oak-finish--1psgkx.jpg",
          img3: "https://ii1.pepperfry.com/media/catalog/product/s/y/568x625/symes-solid-wood-bench-in-honey-oak-finish-by-amberville-symes-solid-wood-bench-in-honey-oak-finish--cotgyk.jpg",
          Brand: "Amberville",
          Dimensions:
            " H 37 x W 48 x D 19; Seating Height - 18 (All dimension in inches)",
          Weight: " 20 KG",
          Colour: "Honey Oak",
          Warranty: " 36 Months' Warranty",
          Assembly: " No Assembly Required",
          Primary_Material: " Sheesham Wood",
          Room_Type: " Living Room",
          Seating_Height: " 18",
        },
        {
          Title: "Ludwig Solid Wood Settee In Natural Finish",
          Price: 52999,
          offer:63,
          img1: "https://ii1.pepperfry.com/media/catalog/product/l/u/568x625/ludwig-solid-wood-bench-in-natural-finish---bohemiana-by-pepperfry-ludwig-solid-wood-bench-in-natura-t1fmh3.jpg",
          img2: "https://ii1.pepperfry.com/media/catalog/product/l/u/568x625/ludwig-solid-wood-console-table-in-natural-finish---bohemiana-by-pepperfry-ludwig-solid-wood-console-8hcngq.jpg",
          img3: "https://ii1.pepperfry.com/media/catalog/product/l/u/568x625/ludwig-solid-wood-console-table-in-natural-finish---bohemiana-by-pepperfry-ludwig-solid-wood-console-kpvezc.jpg",
          Brand: "Bohemiana",
          Dimensions: " H 24 x W 35.5 x D 15.25 (All Dimension Are In Inches)",
          dims: [24, 35.5, 15.25],
          Weight: " 30 KG",
          Colour: " Natural",
          Warranty: "36 Months' Warranty",
          Assembly: " Carpenter Assembly",
          Primary_Material: "Mango Wood",
          Room_Type: "Living Room",
        },
        {
          Title: "Orpha Metal Settee In Grey Colour",
          Price: 32999,
          offer: 76,
          dims: [22, 41.5, 20],
          img1: "https://ii1.pepperfry.com/media/catalog/product/o/r/568x625/orpha-metal-settee-in-grey-colour---bohemiana-by-pepperfry-orpha-metal-settee-in-grey-colour---bohem-uoaipu.jpg",
          img2: "https://ii1.pepperfry.com/media/catalog/product/o/r/568x625/orpha-metal-settee-in-grey-colour---bohemiana-by-pepperfry-orpha-metal-settee-in-grey-colour---bohem-tqsrtm.jpg",
          img3: "https://ii1.pepperfry.com/media/catalog/product/o/r/568x625/orpha-metal-settee-in-grey-colour---bohemiana-by-pepperfry-orpha-metal-settee-in-grey-colour---bohem-mejtxw.jpg",
          Brand: " Bohemiana",
          Dimensions: "H 22 X W 41.5 X D 20 (All Dimension Are In Inches)",
          Weight: " 9.2 KG",
          Colour: " Grey / Black",
          Warranty: " 36 Months' Warranty",
          Assembly: " Carpenter Assembly",
          Primary_Material: "Metal",
          Room_Type: " Living Room",
          Seating_Height: "17",
        },
        {
          Title: "Maurya Solid Wood Settee In Honey Oak Finish",
          Price: 43999,
          offer: 50,
          img1: "https://ii1.pepperfry.com/media/catalog/product/m/a/568x625/maurya-solid-wood-settee-in-honey-oak-finish---mudramark-by-pepperfry-maurya-solid-wood-settee-in-ho-edv7r6.jpg",
          img2: "https://ii1.pepperfry.com/media/catalog/product/a/m/568x625/amherst-settee-in-honey-oak-finish-by-amberville-amherst-settee-in-honey-oak-finish-by-amberville-lre7kf.jpg",
          img3: "https://ii1.pepperfry.com/media/catalog/product/a/m/568x625/amherst-settee-in-honey-oak-finish-by-amberville-amherst-settee-in-honey-oak-finish-by-amberville-gavfmr.jpg",
          Brand: "Mudramark",
          Dimensions: "H 37 x W 47 x D 19 (In Inches)",
          dims: [37, 47, 19],
          Weight: "25 KG",
          Colour: "Honey Oak",
          Warranty: "36 Months' Warranty",
          Assembly: " No Assembly Required",
          Primary_Material: "Sheesham Wood",
          Room_Type: "Living Room",
          Seating_Height: "18",
        },
        {
          Title: "Maurya Solid Wood Settee In Passion Mahogany Finish",
          Price: 43999,
          offer: 50,
          dims: [ 36 , 63, 20],
          img1: "https://ii1.pepperfry.com/media/catalog/product/m/a/568x625/maurya-solid-wood-settee-in-passion-mahogany-finish---mudramark-by-pepperfry-maurya-solid-wood-sette-axebb2.jpg",
          img2: "https://ii1.pepperfry.com/media/catalog/product/a/m/568x625/amherst-settee-in-passion-mahogany-finish-by-amberville-amherst-settee-in-passion-mahogany-finish-by-nbf4mc.jpg",
          img3: "https://ii1.pepperfry.com/media/catalog/product/m/a/568x625/maurya-solid-wood-handcrafted-settee-in-passion-mahogany-finish-by-mudramark-maurya-solid-wood-handc-pqeb47.jpg",
          Brand: "Mudramark",
          Dimensions: "H 36 x W 63 x D 20(all dimensions in inches)",
          Weight: "25 KG",
          Colour: "Passion Mahogany",
          Warranty: "36 Months' Warranty",
          Assembly: "No Assembly Required",
          Primary_Material: "Mango Wood",
          Room_Type: "Living Room",
          Seating_Height: "18",
        },
        {
          Title: "Thiva Metal Settee In Matte Black Finish",
          Price: 17999,
          offer: 26,
          dims: [24, 46, 20],
          img1: "https://ii1.pepperfry.com/media/catalog/product/t/h/568x625/thiva-metal-bench-in-black-matte-finish---bohemiana-by-pepperfry-thiva-metal-bench-in-black-matte-fi-5ozqzk.jpg",
          img2: "https://ii1.pepperfry.com/media/catalog/product/t/h/568x625/thiva-metal-bench-in-black-matte-finish---bohemiana-by-pepperfry-thiva-metal-bench-in-black-matte-fi-qzpbxl.jpg",
          img3: "https://ii1.pepperfry.com/media/catalog/product/t/h/568x625/thiva-metal-bench-in-black-matte-finish---bohemiana-by-pepperfry-thiva-metal-bench-in-black-matte-fi-eef09a.jpg",
          Brand: "Bohemiana",
          Dimensions: "H 24 x W 46 x D 20(All dimension are in Inches)",
          Weight: "21 KG",
          Colour: "Black",
          Warranty: " 36 Months' Warranty",
          Assembly: "No Assembly Required",
          Primary_Material: "Iron",
          Room_Type: " Living Room",
          Seating_Height: "15",
      },        
        {
          Title: "Rafles Settee in Brown Colour",
          Price: 19900,
          offer: 12,
          dims: [34, 46, 19],
          img1: "https://ii1.pepperfry.com/media/catalog/product/r/a/568x625/rafles-settee-in-brown-colour-by-stories-rafles-settee-in-brown-colour-by-stories-zfjims.jpg",
          img2: "https://ii1.pepperfry.com/media/catalog/product/r/a/568x625/rafles-two-seater-bench-in-brown-colour-by-stories-rafles-two-seater-bench-in-brown-colour-by-storie-6zfwp4.jpg",
          img3: "https://ii1.pepperfry.com/media/catalog/product/r/a/568x625/rafles-two-seater-bench-in-brown-colour-by-stories-rafles-two-seater-bench-in-brown-colour-by-storie-arnvva.jpg",
          Brand: "Stories",
          Dimensions:
            "H 34 x W 46 x D 19; Seating Height : 18(all dimensions are in inches)",
          Weight: "10 KG",
          Warranty: "12 Months' Warranty",
          Assembly: "No Assembly Required",
          Primary_Material: "Teak Wood",
          Room_Type: "Living Room",
          Seating_Height: "18",
      },
      {
        Title: "Symes Settee In Honey Oak Finish",
        Price:31999 ,
        offer: 39,
        dims: [37, 48, 19],
        img1: "https://ii1.pepperfry.com/media/catalog/product/s/y/568x625/symes-settee-in-honey-oak-finish---amberville-by-pepperfry-symes-settee-in-honey-oak-finish---amberv-sgyybd.jpg",
        img2: "https://ii1.pepperfry.com/media/catalog/product/s/y/568x625/symes-settee-in-honey-oak-finish-by-amberville-symes-settee-in-honey-oak-finish-by-amberville-auoify.jpg",
        img3: "https://ii1.pepperfry.com/media/catalog/product/a/m/568x625/amherst-settee-in-honey-oak-finish-by-amberville-amherst-settee-in-honey-oak-finish-by-amberville-p18tno.jpg",
        Brand: "Amberville",
        Dimensions:
          "H 34 x W 46 x D 19; Seating Height : 18(all dimensions are in inches)",
        Weight: "20 KG",
        Warranty: "36 Months' Warranty",
        Assembly: "No Assembly Required",
        Primary_Material: "Sheesham Wood",
        Room_Type: "Living Room",
        Seating_Height: "18",
      },
      {
        Title: "Thiva Metal Settee In Grey Finish",
        Price:17999 ,
        offer: 26,
        dims: [24, 46, 20],
        img1: "https://ii1.pepperfry.com/media/catalog/product/t/h/568x625/thiva-metal-bench-in-grey-finish---bohemiana-by-pepperfry-thiva-metal-bench-in-grey-finish---bohemia-92iksq.jpg",
        img2: "https://ii1.pepperfry.com/media/catalog/product/t/h/568x625/thiva-metal-bench-in-grey-finish---bohemiana-by-pepperfry-thiva-metal-bench-in-grey-finish---bohemia-rzzpsq.jpg",
        img3: "https://www.pepperfry.com/thiva-metal-bench-in-grey-finish-bohemiana-by-pepperfry-1903474.html?type=clip&pos=10:1&cat=4180&total_result=11&variation_id=209072&sort=ranking|desc",
        Brand: "Bohemiana",
        Dimensions:
          "H 34 x W 46 x D 19; Seating Height : 18(all dimensions are in inches)",
        Weight: "21 KG",
        Warranty: "36 Months' Warranty",
        Assembly: "No Assembly Required",
        Primary_Material: "Iron",
        Room_Type: "Living Room",
        Seating_Height: "15",
      },
      {
        Title: "Thiva Metal Settee In Gold Finish",
        Price:17999 ,
        offer: 26,
        dims: [24, 46, 20],
        img1: "https://ii1.pepperfry.com/media/catalog/product/t/h/568x625/thiva-metal-bench-in-gold-finish---bohemiana-by-pepperfry-thiva-metal-bench-in-gold-finish---bohemia-6f2qjl.jpg",
        img2: "https://ii1.pepperfry.com/media/catalog/product/t/h/568x625/thiva-metal-bench-in-gold-finish---bohemiana-by-pepperfry-thiva-metal-bench-in-gold-finish---bohemia-imalfg.jpg",
        img3: "https://ii1.pepperfry.com/media/catalog/product/t/h/568x625/thiva-metal-bench-in-gold-finish---bohemiana-by-pepperfry-thiva-metal-bench-in-gold-finish---bohemia-an91k3.jpg",
        Brand: "Bohemiana",
        Dimensions:
          "H 34 x W 46 x D 19; Seating Height : 18(all dimensions are in inches)",
        Weight: "21 KG",
        Warranty: "36 Months' Warranty",
        Assembly: "No Assembly Required",
        Primary_Material: "Iron",
        Room_Type: "Living Room",
        Seating_Height: "15",
      },   
      ];
    
      